### ISSUE TITLE
Exception reading message

### ISSUE THREAD

**Issue by krumok** [foens/hpop#36] opened 2015-06-22 09:09 UTC
Hi, i'm getting this error:
System.ArgumentException: Nome di codifica 'ISO8859-15' non supportato.
Nome parametro: name
   in System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   in System.Globalization.EncodingTable.GetCodePageFromName(String name)
   in OpenPop.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
   in OpenPop.Mime.MessagePart.ParseBodyEncoding(String characterSet)
   in OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers)
   in OpenPop.Mime.MessagePart.GetMessagePart(Byte[] rawMessageContent)
   in OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody)
   in OpenPop.Mime.MessagePart.ParseBody(Byte[] rawBody)
   in OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers)
   in OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody)
   in OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber)

using  GetMessage method
This happens on a specific message, on other messages works successfully.
Now i bypass this message with try catch to avoid blocking email pop but i cannot read the indicted message.

**Comment by JoshKeegan** [comment] 2015-06-22 13:41
Fixed in PR #37 
Could also be fixed client-side using either the custom mappings or the fallback encoder (see EncodingFinderTests for usage).

**Comment by krumok** [comment] 2015-06-22 15:35
ok thank you!
using EncodingFinder.AddMapping("ISO8859-15", System.Text.Encoding.UTF8)
i solve this issue now the unknown message was received correctly
i have another issue and i will open another thread
thank you again

**Comment by JoshKeegan** [comment] 2015-06-22 16:19
Be aware that you are mapping "ISO8859-15" to UTF8, which isn't the specified encoding & so could cause problems. Changing 
```csharp
System.Text.Encoding.UTF8
``` 
to 
```csharp
Encoding.GetEncoding("iso-8859-15")
```
will mean that the content gets read with the correct Charset.
This might also be the cause of you're new issue.

**Comment by krumok** [comment] 2015-06-22 19:46
Hi, thank you for your prompt reply!
No the new issue #38 is for another message.
The message in this issue #36 is solved, but I will consider your suggestion about charset
Thank you again

**Closed** 2015-06-24 18:34 UTC
